---
title: "Portfolio3"
output: html_document
---

```{r}
library(dplyr)
library(tidytext)
library(janeaustenr)
library(widyr)
library(igraph)
library(ggraph)
library(shiny)
library(tidyverse)
```

```{r}
fun = function(df, name, cor){
  austen_section_words <- df %>%
    filter(book == name) %>%
    mutate(section = row_number() %/% 10) %>%
    filter(section > 0) %>%
    unnest_tokens(word, text) %>%
    filter(!word %in% stop_words$word)
  word_cors <- austen_section_words %>%
    group_by(word) %>%
    filter(n() >= 20) %>%
    pairwise_cor(word, section, sort = TRUE)
  word_cors %>%
    filter(correlation > cor) %>%
    graph_from_data_frame() %>%
    ggraph(layout = "nicely") +
    geom_edge_link(aes(edge_alpha = correlation, width = 0.4), show.legend = FALSE) +
    geom_node_point(color = "lightblue", size = 5) +
    geom_node_text(aes(label = name), repel = TRUE) +
    theme_void()
}
```


```{r}
ui <- fluidPage(
  titlePanel("Correlation of Vocabulary in Books Written by Jane Austen"), #change
  sidebarLayout(
    sidebarPanel(
      sliderInput("cor", "Select the minimum correlation between words to visualize", 0.15, min = 0, max = 0.4, step = 0.01),
      selectInput("name", "Select the name of the book", unique(austen_books()$book))),
    
    mainPanel(
      plotOutput("network")
    )
  )
)

server <- function(input, output) {
  df_sub <- reactive({
    #austen_books() %>%
    #  filter(book == input$name)
    fun(austen_books(), input$name, input$cor)
   })
  
  output$network <- renderPlot(df_sub())
}

app <- shinyApp(ui, server)
app
```
